/**
 * The sending half, behind an interface small enough to fake.
 *
 * `MailSender` takes one shape of message and offers no way to build another:
 * one recipient, a fixed sender, a plain-text body, and the three threading
 * headers. There is no `cc`, no `bcc`, no `attachments`, no `html` and no
 * `from` — not because a caller is trusted to leave them out, but because the
 * type has nowhere to put them. Everything an admin can influence is the body.
 *
 * Three transport settings are not configurable and must stay that way:
 *
 *  - `rejectUnauthorized: true`. A certificate that does not verify means
 *    something is between this process and the mail server.
 *  - `disableFileAccess` and `disableUrlAccess`. Nodemailer will otherwise
 *    read files and fetch URLs referenced by a message while building it. This
 *    application must never fetch a URL that came out of an email.
 *  - `logger: false`. The default logger writes the SMTP conversation —
 *    including `AUTH` — to stdout.
 */

import { smtpPassword, type SmtpConfig } from "./config";

/** Everything a reply can be. Deliberately not extensible. */
export type OutboundMail = {
  /** Exactly one recipient, resolved from the thread — never from a client. */
  to: string;
  subject: string;
  /** Plain text only. There is no HTML field on purpose. */
  text: string;
  /** `<...>`-wrapped, generated by us before the send so it can be stored. */
  messageId: string;
  inReplyTo?: string;
  references?: string[];
};

export type SendResult = {
  /** What the server said it accepted, for the log line. Never stored raw. */
  accepted: number;
};

export interface MailSender {
  send(mail: OutboundMail): Promise<SendResult>;
  close(): Promise<void>;
}

export type MailSenderFactory = (config: SmtpConfig) => Promise<MailSender>;

/**
 * Nodemailer is imported lazily.
 *
 * The module is only reachable from a code path that has already checked
 * `INBOX_SMTP_ENABLED`, so a backend with sending switched off never loads a
 * mail library — and never fails to boot because of one.
 */
export const createMailSender: MailSenderFactory = async (config) => {
  const nodemailer = await import("nodemailer");

  const transport = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth: { user: config.user, pass: smtpPassword() },

    // No SMTP conversation in the logs. See the file header.
    logger: false,
    debug: false,

    // TLS verification is not negotiable. When `secure` is false this is a
    // STARTTLS connection, and `requireTLS` makes the upgrade mandatory rather
    // than best-effort, so credentials never cross a cleartext socket.
    requireTLS: !config.secure,
    tls: { rejectUnauthorized: true, minVersion: "TLSv1.2" },

    // Nodemailer must not touch the filesystem or the network on behalf of a
    // message's content. Nothing here sends attachments or HTML, and these two
    // make that true even if a future edit tries.
    disableFileAccess: true,
    disableUrlAccess: true,

    connectionTimeout: 15_000,
    greetingTimeout: 15_000,
    socketTimeout: 30_000,
  });

  return {
    async send(mail) {
      const info = await transport.sendMail({
        from: config.from,
        sender: config.from,
        to: mail.to,
        subject: mail.subject,
        text: mail.text,
        messageId: mail.messageId,
        inReplyTo: mail.inReplyTo,
        references: mail.references,
        // Belt and braces alongside the transport options: an empty attachment
        // list and no html field, stated at the call site so a reader of this
        // function does not have to go looking for what is missing.
        attachments: [],
        headers: {},
      });

      return { accepted: Array.isArray(info.accepted) ? info.accepted.length : 0 };
    },

    async close() {
      try {
        transport.close();
      } catch {
        // Best-effort: failing to hang up is not a failure of a sent message.
      }
    },
  };
};
