import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import {
	mkdtemp,
	mkdir,
	readFile,
	rm,
	symlink,
	writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, test } from "node:test";

import {
	buildCspFile,
	buildPolicy,
	inventoryBuild,
	inventoryHtml,
	quoteCaddy,
	renderCaddyImport,
	sha256Source,
} from "../build-csp.mjs";

const temporaryDirectories = [];

async function temporaryDirectory() {
	const directory = await mkdtemp(join(tmpdir(), "peptides-csp-test-"));
	temporaryDirectories.push(directory);
	return directory;
}

async function fixture(files) {
	const root = await temporaryDirectory();
	for (const [relativePath, contents] of Object.entries(files)) {
		const path = join(root, relativePath);
		await mkdir(join(path, ".."), { recursive: true });
		await writeFile(path, contents, "utf8");
	}
	return root;
}

function digest(source) {
	return `'sha256-${createHash("sha256").update(source, "utf8").digest("base64")}'`;
}

afterEach(async () => {
	await Promise.all(
		temporaryDirectories.splice(0).map((directory) =>
			rm(directory, { force: true, recursive: true }),
		),
	);
});

test("inventories exact inline bytes, JSON-LD, decoded style attributes, and skips external scripts", async () => {
	const script = "\n  window.answer = 42;\n";
	const jsonLd = '{"@context":"https://schema.org","name":"A & B"}';
	const style = "\n.card { color: red; }\n";
	const decodedStyleAttribute = 'content: "A & B"; width: 2px';
	const root = await fixture({
		"z-last.html": [
			"<!doctype html>",
			'<script src="/_astro/app.js">ignored()</script>',
			`<script>${script}</script>`,
			`<script type="application/ld+json">${jsonLd}</script>`,
			`<style>${style}</style>`,
			'<div style="content: &quot;A &amp; B&quot;; width: &#x32;px"></div>',
		].join(""),
		"nested/a-first.HTML": `<script>${script}</script>`,
	});

	const inventory = await inventoryBuild(root);

	assert.equal(inventory.htmlFileCount, 2);
	assert.deepEqual(inventory.scriptHashes, [digest(script), digest(jsonLd)].sort());
	assert.deepEqual(inventory.styleElementHashes, [digest(style)]);
	assert.deepEqual(inventory.styleAttributeHashes, [
		digest(decodedStyleAttribute),
	]);
	assert.equal(sha256Source(script), digest(script));
});

test("renders stable, sorted, Caddy-importable output with explicit restrictive directives", () => {
	const inventory = {
		htmlFileCount: 3,
		scriptHashes: ["'sha256-z='", "'sha256-a='"],
		styleElementHashes: ["'sha256-y='"],
		styleAttributeHashes: ["'sha256-b='"],
	};

	const first = renderCaddyImport(inventory);
	const second = renderCaddyImport(structuredClone(inventory));
	const policy = buildPolicy(inventory);

	assert.equal(first, second);
	assert.match(first, /^# Generated by deploy\/build-csp\.mjs/m);
	assert.match(first, /^# Mode: enforced\.$/m);
	assert.match(first, /^header Content-Security-Policy "/m);
	assert.doesNotMatch(first, /Content-Security-Policy-Report-Only/);
	assert.ok(policy.indexOf("'sha256-a='") < policy.indexOf("'sha256-z='"));

	for (const directive of [
		"default-src",
		"script-src",
		"style-src",
		"connect-src",
		"img-src",
		"font-src",
		"frame-ancestors",
		"base-uri",
		"form-action",
		"object-src",
	]) {
		assert.match(policy, new RegExp(`(?:^|; )${directive} `));
	}

	assert.doesNotMatch(policy, /'unsafe-inline'|'unsafe-eval'/);
	assert.match(policy, /script-src-attr 'none'/);
	assert.match(policy, /style-src-attr 'unsafe-hashes' 'sha256-b='/);
});

test("renders the same policy under a genuine report-only header", () => {
	const inventory = {
		htmlFileCount: 1,
		scriptHashes: ["'sha256-script='"],
		styleElementHashes: ["'sha256-style='"],
		styleAttributeHashes: [],
	};

	const enforced = renderCaddyImport(inventory);
	const reportOnly = renderCaddyImport(inventory, "reportOnly");

	assert.match(reportOnly, /^# Mode: report-only\.$/m);
	assert.match(
		reportOnly,
		/^header Content-Security-Policy-Report-Only "/m,
	);
	assert.doesNotMatch(
		reportOnly,
		/^header Content-Security-Policy "/m,
	);
	assert.equal(
		reportOnly
			.split("\n")
			.find((line) => line.startsWith("header "))
			.replace("Content-Security-Policy-Report-Only", "Content-Security-Policy"),
		enforced.split("\n").find((line) => line.startsWith("header ")),
	);
	assert.throws(
		() => renderCaddyImport(inventory, "disabled"),
		/unsupported CSP mode/,
	);
});

test("a content change produces a different hash and deterministic rebuilds are byte-identical", async () => {
	const root = await fixture({
		"index.html": "<script>const value = 1;</script>",
	});
	const output = join(await temporaryDirectory(), "csp.caddy");

	await buildCspFile(root, output);
	const first = await readFile(output, "utf8");
	await buildCspFile(root, output);
	const second = await readFile(output, "utf8");
	assert.equal(second, first);

	await writeFile(
		join(root, "index.html"),
		"<script>const value = 2;</script>",
		"utf8",
	);
	await buildCspFile(root, output);
	const changed = await readFile(output, "utf8");

	assert.notEqual(changed, first);
	assert.match(changed, new RegExp(digest("const value = 2;").replaceAll("+", "\\+")));
	assert.doesNotMatch(changed, new RegExp(digest("const value = 1;").replaceAll("+", "\\+")));
});

test("writes report-only output atomically when explicitly requested", async () => {
	const root = await fixture({
		"index.html": "<script>globalThis.ready = true;</script>",
	});
	const output = join(await temporaryDirectory(), "csp-report-only.caddy");

	await buildCspFile(root, output, "reportOnly");

	const generated = await readFile(output, "utf8");
	assert.match(
		generated,
		/^header Content-Security-Policy-Report-Only "/m,
	);
});

test("Caddy quoting escapes quotes and backslashes and rejects header injection", () => {
	assert.equal(quoteCaddy('one "two" \\\\ three'), '"one \\"two\\" \\\\\\\\ three"');
	assert.throws(() => quoteCaddy("safe\nheader Evil true"), /control character/);
	assert.throws(() => quoteCaddy("safe\0unsafe"), /control character/);
});

test("fails closed on malformed relevant markup, forbidden inline handlers, and javascript URLs", () => {
	assert.throws(
		() => inventoryHtml("<script>unfinished", "broken.html"),
		/broken\.html: missing closing <\/script>/,
	);
	assert.throws(
		() => inventoryHtml('<div style="unterminated></div>', "broken.html"),
		/unterminated quoted attribute/,
	);
	assert.throws(
		() => inventoryHtml('<button onclick="submit()">Pay</button>', "bad.html"),
		/inline event handler "onclick" is forbidden/,
	);
	assert.throws(
		() => inventoryHtml('<a href="java&#x73;cript:alert(1)">Bad</a>', "bad.html"),
		/javascript: URL .* is forbidden/,
	);
});

test("a failed scan leaves an existing output untouched", async () => {
	const root = await fixture({
		"index.html": "<style>unfinished",
	});
	const outputDirectory = await temporaryDirectory();
	const output = join(outputDirectory, "csp.caddy");
	await writeFile(output, "known-good\n", "utf8");

	await assert.rejects(
		buildCspFile(root, output),
		/missing closing <\/style>/,
	);
	assert.equal(await readFile(output, "utf8"), "known-good\n");
});

test("rejects missing/empty builds and symlinks instead of silently omitting input", async () => {
	const missing = join(await temporaryDirectory(), "missing");
	await assert.rejects(inventoryBuild(missing), /cannot inspect build directory/);

	const empty = await temporaryDirectory();
	await assert.rejects(inventoryBuild(empty), /contains no HTML files/);

	const root = await fixture({ "index.html": "<main>ok</main>" });
	await symlink(join(root, "index.html"), join(root, "linked.html"));
	await assert.rejects(inventoryBuild(root), /symbolic links are not allowed/);
});
